---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBvpnmEg/1MZeQM2vBRbxzUpqM1wJnWLbt8dosSlKgDR5bDUWErC8dRVSaIbwrhA7V9vb51Gg6hnSQLy3gqMjDu7Ok5YLPVuN1zDc7iU2JjwkvVExVJSqFH962VMLsikXFz5gzqpbR8VG5R3pHwtSodUc/vmtvyUbOeMU79uNfx0vsOJ/8/Z+NbJjebQJ2LXqqAWGSYLbGBvwbzFECvbDdCUrRWLsUkMn+Du8MNLcCywMasRCdj9CH2eEy8l5mcOioCw5bZtDsAWiqOypq2jgpVK0aOIc7sclwyJag6xqrgWFpraRGIm6lOlJxQOlxs+xeoxENozfqvLoXE6fZ1ctQ9kNK8sbyrvqLw99xjws/SAQOMf664IGveOEgC+6rhp5ZgELbfsIH2VpQbbXfgdA793TA7gTTTlkwJtjOPnYm8lYKcuCJow4EssUAhtAylG0zjKOuaq/zWNy/XZIO3b9mUPD8UqWQj0Lf/RuDIE0iiK+PtIyfM1a/egucfhiLQCwPDXH03IjUUdAQUV+LO9gqKAShcgZqKyHdfyfquA7r+LXMAw1GgaU1ZnBTUQaQ9XdFQkWFKIZ11C3IQ5UBMji+ZOvEKepgT6coOvbUIRWJlufkO1PIQwDNSItihrWNfaA1O8XqaxxCQTg+udYzTY/WEU4h8N9PSOo33bVEk17sB6ZiQijDMqO755g0gjoWpU0625xXuF3MvJPCODcAJHoG2iP7xr4cQ7Ve774Z70E6HUA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
