---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: infrastructure
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgC182DXu2VH5Db2uSat+j4ZUnsIRHIXkkhBP7hAo2U2153Jkdfv+ENpSJm3JGtMxDOhmdjPNE6NHgo/C7OmCPbIz1alB0U4/pvEjnDzVV+7wyTtQhcd2wop8t9NJWPn151gg6/IOEHOSqMmLgB3MHK+iibu+kf9mHIXLwRS7d5QPJk/T3cs0GJn7l6WSKJtWPXg/U4v4poXx1QywRrlf84oZJyTt6yR9VOG9LEA5RG18lknjK/n1S1IlGJi1PoG+jhhn5EnLx/uhzobo0QqYxIubPsKCl5TRG7agZHZKx9xXM7Seqvx0v0zO85KpPT+2XyBN5e/d2eJTG4H2KZtQMZnwEi7z0rVZL6Zq2HwHSarxr/+PimrEj+2MnWC7T/LvL0MWZusb45IqcV6MBCjS8ezLMh8ol1SkImJlLfZu+X5T4rx+mYrB4nSxc3BtsDy7Ut9pAu8j9pMVFxEbZYsvcfJFUtadY9PXkHJJWsif7GQbnHOLDoLL75KEhJRyCWLc+m1kfzR6h4cfVCZsOm2b4/4lxG3Y0YB3DzqKYsx56idbrnNNSe29St46Akzss19/sfBpVLcLdYUt8hQyoiTf4S9psbRdzl7Owofoet4v9CiDnFmFsQDuzkRSNFgp2Y5uL64p9VRD0/guOT3d9zQR5uGlpaQLAaLSPmku1W/yLAnwRT1Umux7SoljXIBFZdl2Cuec2TTcLLvGhtsL0E+ZZikUxt/UfJCp/04cWBJqKx+Lg==
    MONGO_INITDB_ROOT_USERNAME: AgAbFw5PPzvuHr01DP1EjHDEvSqmvOu1cWJffs+aZRYrgKCdNdQ+mqO192hl41wltsQW2eX403gqB5NlfbRjFC+ImhGVqhwiF/ebvg78BVLE1sb5WTzLJAkZEbi36IJgxZesMuIAD+0Eo//t5FbIU1QbLPLTvawqWLARZ3U5xDTug6EP1C8Q/OpPs1f7ENiEUxseU8inRvLmWwJn6sfmpIOcYaCW5C1LmA+aVTv2AkEKg941XhgYKJNmAHeMKQWSlDC4LiO8Itob3u0EX4BbkOylaC8504NncS0l8Bmh83M2jKYODliX2YdROjrxOytuqSBAFFEVy/HjNgQwjk5N6jqNtJK9DBaoLeWxPVzh/ncTJj8Fby1yVuXcoJPAq/qstX1zZaK2l0rEl30X8GVgpSbHImg+CgjvD0kiV/YkbOP/JJVO+JczW0xs1j9dgmSfMnALcEjVqNp2W86SutkINbcyXTgciJlJdfJxnqOti77yv6RcAxX6lPzwdTpawsfcqM8tTTNDN60Od2JTjo7sfMJs8jvq1x01EX26PE8UQHidpgPeF3vYrenyayQNbpeTEYJdWiXgbCNCYLoA4rHaPFIj2tH8k7xbhMxkpK42pIvvK63r18d2rj4RYcH/ifgJw8Zq/WzPPuvpoYerJy570fkpaYtrTuD9cDd0wsIVU7mX8nXlJlRVnUI9ygx/hPkwQj6uIToG
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: infrastructure
