---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: infrastructure
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgATPbBoyfqzojD2wnExx5OIbAVBghe49Hc2E98tPtvN/k89S5gEdBYtgM9wKVqUksDVgXikK65aAZ4H3nJ/Gt4krPnCu+lFP2QavoyAtsrdD9v2dMZvj8bKrBrIZYfCTkMH/uT0+Y+I7g+yo19gbcqX7R7PO8PixkPpBuMS+E/Pfe0DcVNnjscicpy2ibmyy8CmiK8sUqkSj9JycS76llew3cOhDcQWA+lZ14P/ppFtzYZGpiGbxsYdSabvNc791K3yr35PBfewdvDnMKrBoF/59+pVkSyGU0NYxqF12+Cm1hQhb1h8BpwBsiiF/6WAsjIUVTz3tsAQyDxHkFqEWNkmi9UiM6GdLkNcI2pu82gL4Gf8UNNDl0AgF9lyonUBinZItklFtsNHiMoZ6OKorm9LnearNJzBnJsT14TO8srZxldfxJ1NoFU0bMChkSvrRC5kq/hvmg0gw5cZqqUdaq/hga0Yib1LEu/zj0TP3nfvwATs2EdpeJqBeWoclMKEe7Jqa3b4nNPx3T/Shofi98hjBSCtybrC5jXeU8UAnmpPWaOWOQzu+Lt2wFas3NsktnOIozut2JRYfVqHILm9DoF7V7yPxzVziTBbv1d3n2aUYVKrUV76EdT8C5Hjcbn84vffUfMLk0FcfnT0Gcyz03LCDPMti+NQqg15D77L+Zyn55/ochQ3WmWSBg7x6YPB3PdXH7QoDBsStu9mhtsPIBjZgtrXMeKqWotPHdWYvM57kw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: infrastructure
