---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: infrastructure
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgC1QjrHk9Y1HgNGQxZMjJnlVLH6Pv9jx5NjtyDPYkiGk2Elav6vV2R62Z8loFxgWSq4y3vcStmJtD0BUxjXGFmmG3jN0wbkvQMgfsGe0wpe+UqGoPVzzxNl/9KCt6TiUndsLpLpSq/UJTBPVw54Vl3FVhcEwDU/CNDofnW+MMK5aFlNJViZeLuuCc0hLx4Pde5dq+/wQliq9ZZweFllgr5jSRzhhF9dKv6Vy+jfjXPODpa15n0LlJUmgRNbpD8TTJLEX/TdBVkHsFw5SACzuI55WjleN8JI0zmbutAoQdxhC4kJP3b/JiFwNF1GMc1EtUXad7fhO4NmD3cpIpShj7KmM8i1ZFhCAhvAnVJxj+AGZK6o0gCCKlQk2KvDd+UqJ7SeH+j3T43sSGBZnwB0/bcHCYVV9paVR/baf5R4XvUN8SlrMvNB/NB9m1HU4BGPI/gXglkStOWkAWBNS/j7sSvej7AnUYOBBJ/Mzl+lSpqdFFOsloC5yjqsm7uodrAc9SCA5ZEeSupUpNj7+d6tdsa/KoffMgK2ILgMRXjOHfMHW2lgztR/LRYhLphdLVlfJRyPUupGLt1NzT7QiEKThBM+vBzw5wVnNCxsf3/Wx9jtUyXrAWtTli+Lg6z76aB2kmrV/hJsEuEwjrOoaLxcUK+drAmfB87P/eiOu6QI0aYfcEhO4pzjNmci3e5xIeuM2OqfvSW/uIIH5eP1q9D7IYaHGlY2bkyI6K6xaUhUNytIBQ==
    RABBITMQ_DEFAULT_USER: AgBzc+AczsUnTUDZm5XNU0tjMsTjm2aAN2MTuojmmMCCVAcFMUo+4+kex8s1txr6+cVDHVR9s0M9pVd5F2VX4o+m0XSUOYTRQm5bCNso9DDk1WDr0wwvho8Xl64LjCvdnKNs8OTYXI3Fd9amQtycWcW0fL2Fx6zXmamIsMTu0rSG++uqBazQ2/7t4SgZfxxnzsPSu2OhmzycvOg+PDD6C/sz7kTQspOl3GggTN568MiVyeMgkvFxCGJ9vpxEMkBSWMpOANNjdsaDvnyKvIqeQkltfVjttvpVjAPNVKj2MaVz8e8zMC/tUnEE3lMlQbzQdnbhVSu9am4zfUzkFNeNbC0iJotoF73BM1FO0jCEH4L81PNo/osYDwAWeMWuA9Nd595SbbbRe4QQ1KV7iUDE6SMFVyHkVzvkAb4jcopgizl4Cw5hBlfITh5Uh3ea1A4pVmkehavZlfYIPsVkf7gXpelE0IWeqGRYOCsG7DyGkpRKt/iVXnuGM2VNAGQlU4Vvu1G8dS0wQB82YoPg7pQr3cdTsesOPYlPEA8TEFBt0Lg+4w0A1J3tvVVskiaNDBHcXvl5a5SmEHMch9VkpcodSN5LGACt0MLF+UuVWoFpDZvHhf7JYHutOwm9sVHrJfaxWsxI294WTCO1Amlfq7+Lhz0ZpVzfqlg5AkttsODXagR8fX8uJ+KJH5PDxHm/PvxAGQU6BRY=
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: infrastructure
