---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payments-api-secret
  namespace: gamestore
spec:
  encryptedData:
    ConnectionStrings__DefaultConnection: AgAtjn7PdJwjof+RsCmCvt/TasJq0uI7HCF/NWxPqhHOPNecY9A1FWEKkaCowyNNin7sIZHnHsw2vmZMiwaRjHv6tNvunD8/RoMdQTuS0mNv/KUpMFyF1ZWqE8KTW/HPiKZKqz+w0QqT8AkXEVKevsn7ZS3ou68DZUt9SLmrWnFUkJ1NvtgDRDgpevfgpXTSJhAscizY6gFoyFS2NcHhfS1bTqA91vfRleQfL+prO/gHWykc44tLkIgP+yt85v5vXxevea818KKHvuYrKZnEhvGj8KI+t+G4fal6ZaO0hy3myJKkoIG6dauTYluTLZ2gAMadPMsMJDFbvd20ZX6jlfV1y4CeH9KdEwgWrY1WrmHd6aCghY9mus017yKfERtQnrlGJcH2SRfYxINZIrlUuX7skS2msJvxnGn+VWVRikA4BywyJIMPFsE+Mu/fwEsTNMb3DUZcRpWdzdrMP/ZAd1eRVW5lhnD87baKNTt6GFfLk3vdTBvWlDzEcfJd8g15vPN97pWfQP8YmJ8cJmIt4WcM3QzSDhwQXbteXAfpS6lpZru5gq/qCG3ShxPc/vSkZ+ZQKWk3JlTO7kYBd5GWOnKYr6TXWw4G92GAtDSdaXzDp3YGl3w+fxbsKLY9DNv2UrXMdUwb4BDjMCTOLHl1jpSan5idv7NGrDbSRTt41y7ZUDiTgHH8iB8fEDPrCspoppsAP+RG+E1ZFC0ZwJFgL8z7eamrksu2D33coYoxb7ifvOWhjxjsMZSG/fac7YfrCAGKD95MeDD4ZRLwQdSLzp628CU0FrkmyExeKfY3uPWKNkWIqi1UeH7wlmKVnvvGlq73M3eRh0QqeJLeMMoxkchnQTk5FTCpyNh7aZnmE1QmyZXMdJ+fgcpBOi8FjQ3Ikr5of9Y8
    RabbitMQ__Password: AgBQfGncF1u/nQwuVZPG4NB5ncu+Aap0Dpn5mFoxDhOGESLF19CNBCmKRbgRZHPsBF14kBsOuRg+VB4pHmIP/PRNiqsUSR733SsOevb2xpDG2AjCKzjbBBSEVDy3qYukdk1n+n5bX3hMsxXl7vOUk4cbx/+oOIsH+OCfWygIUen9CvvZ/a6vZtYewcPY/15bdZB5ARstqSvVn3zrv9u2xFAX7dZc+xEH0YpM/oIacog/jcl03ZAPyaSmm0Hm8BCUejtborWSypEoyE+A52vK4JPVMHDWRdGT4ubgKfUUUCp/ScBZ396t0ipRogTOwUnlRv+0U82HpcP/hnY6ddpg25ERJmB+a5b9dmfjHNTS0mTQiCopuzXluccRwD05l+eMkmtL4wxuicFMn1M8/yILR34fsHS4WvzSH2K3ZRbxDVRcouefX63Ao/fG0+MF4MK7u3km2cbgElJGobKY9jYuPEziTk65I64sqpjgTWQhiiQe8XzKjbQ8qDDkM3m7xWgRXoJx1i8PKK8iuIxF6JVU5+MlIi/Sh8iIovtuonKYcI6MikZLKBvjQK/LY9bc0h0+n9HjXuwFbEgloo15g/P7GgrwazhKWMCkrfOJ1Ksqclv8Q7IG+a3jpL7ZbZnFalMypsNTuQAlfFaBNVlijUJFSfE/h4O2Z+TPDOd/NRZZjgs/ULzpRYyqXdfhZmvGoghyRQ+HX1C6jncvEtDPYz1Lz0Jb4LmDPInxlv0uCSONkB4Y9Q==
  template:
    metadata:
      creationTimestamp: null
      name: payments-api-secret
      namespace: gamestore
