apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
  namespace: gamestore
data:
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_ENVIRONMENT: "Production"
  RabbitMQ__Host: "rabbitmq.infrastructure.svc.cluster.local"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "fcg"
  RabbitMQ__VirtualHost: "/"
  Brevo__SenderEmail: "socialphsilva@gmail.com"
  Brevo__SenderName: "FIAP Cloud Games"
