---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notifications-api-secret
  namespace: gamestore
spec:
  encryptedData:
    Brevo__ApiKey: AgAqtsS4cehjbukkN/cGzbmtcevKmgGXFkYsbVCFORTob0BhMSHxKtrEbwffK9iltNV4wF7ovj3EMrHYr2fg64+cUlo0F2qUanqfFSu+0j87z+CvEZK00W4FqFSXDEwVFv0wmn0wPEsJUPaWcxBRaRRn563oHqH2wLOO0cehva1B5AtUvF0FIo8fXogmNIz4FMp410+VCG49XBj3U88Dii3ce8emHQMd2RlczdHokGTqAhvbZS/TDlk7oaJyLRNdl4uHMZtW4Mb0daqHn1iaAmtsckdDqx0SYlZyzkz78LRZsrZ1LK8ttnj2ksbEIbZrTqqnmgQGVUkkqnQ0d3fbGBLem7ZcZVy9iLB8xQCE1kch5jvRBxp/Xz2/Xxf7+YVTABVdtS0zM322Vhm8hcGuWHinAvoa/GCJcAAF7fx9d8H8/vGSWy6MxJWs6leXENSbkcv3pXgfXlvPfkMCzmO0zWYeKwR+6MXqWh8J0WtsuSorSVvMb5tBaLqWfhfKkHvapIb6ke9pmigot8jDj/LQ6bBUPvbWsRfQxYRqjF5JFqPGAy2oLRqoMcu3rPdSg6ZsZuVL/Kus6WGplDbAbzAegI+TGb/aQODz+oChqUXb85EhHJNnax7NuJGs4sZ1Rwv7SxTcYYV02VpGdt7yH2S11LyECLIy9C896hB8f6RZIwu4ats+4hSj4qQB7pafy0SUO72dbA4INbhO25Bl2VvLMCYSIm9yvX5u4L75BYX4viJjVTKmQVhFecVAa+EUMYpPKlW7LdUSvIpnBBbzDgpTWqRTN11D9og6Oj2vd8PsH54k6aC9E0MdyYH2LA==
    RabbitMQ__Password: AgB58V0ZX8rve11jX7hnbBTPkcSMfrP41KbrfEvNqzB6mkdoGeBxwvsdUT3zXiU7E8u0s7+8GQfdPvPZxixZNr4f+8T2ViIqZirO6wc689zxnGEjNO/CNBNundTMupEIdyBV+lCVcreg1iUrqKubT96PqvRQr6TrPF/gKImgd3eKxE8M7g6EQ3H6ILYgspuBwHz3feDY79t3nC4F5YKO9tnP9I/iuxnoX1mTyPJEz96Eu09RY9HLkvXP/Hg5C4OAQUAnFgQjpUXk0kRj3iPuY4YSqbNMvCDIv3SM9Y0NILO5a9E+zEnJju5WCRBl6AQORmqMdr/6PzstnkeVeONo2+5akwWwBTtpuvr7UrVGpzjwjzK55IpWhmw56zFD7eGj0yXhmYLiBxLfZ6BOb9RqsUB1z76eyUEzzZ3FtJC1REwVb8vdlSeZymMj0rxkl2tlxx7iKATUEYHGHSJ5MAzUCIBbMv+c2wxPdaLKcj0znqe7VAuUP7Eg8YbI2fwZt3x9dsJa2sx6HJKEo1XCLAXgv2uXrg2jfdtRyVImWmCT2MTag06iZBTTFgPGxVRYbWh449OaYbjD8EbstN5DBrgNWn8MAcKtbjag8M4HSpAC8SAOStNBk508Z9ewh3RlES8qdfMPwAn8uriO/FHR4YYdSAxh681HX8a2C+loTsSCVKaEhhEp40qW7kC17SZC6HwuZtUu3dAXiEGemEBAkyP/mdlOHrM6pLCsssuTzWVbzTHFEg==
  template:
    metadata:
      creationTimestamp: null
      name: notifications-api-secret
      namespace: gamestore
