---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-pull-secret
  namespace: gamestore
spec:
  encryptedData:
    .dockerconfigjson: AgCuaLWtXA1kI+5MC5DhA/aUTsVNWqAWnn++xDvT7+cr19rGhFbSnUpfTLPJ/F2geKtLWRLTThD3tYrM3gtyIylc1M43XF/z0xiap36yG1X9xdZbhwVSNSH7u4cPgQEozjd4UdvKva3/CbIVfUkFc7fBUTU9Da/LbfRTraQNAJGz/H+b+UOlqmfywgCt6dcxtU4oSRS+wkqX9lkc74zDznxfG4rrkGx/nGB/YPmTO7WfkzE9Vh3mw1wIISZnz2nuzPY14ligT2C877A6iW9uAH+k0SxllDb/JQe3AaouUkrqELrgnjP6+hCuV1sfnmOLtse9I+tCD8p8D17UhMIrrkh7cpmbl/saC795Mw+MmEkHJzRwcQlp5rJlq4EfDdwJRLm/XQZY0p844B2xxA7YYpFgO/lx70c27YC4yb98pme4YiyVyANtI5Bqv/5OohTCKjYbi3+5xv8UgThl5KDM07c/8GYripuj0nW3nN7uvR8kb6XM60hd1soCfUqZBTdXiyu4yVTsV42TXKEfuwhJlVNDUuQal4NTUwDd8UcoprLSXcphubrlYnhIZw6gcpDkxdKoz3G+lOv8pfi4HLd+5yss26AcBWpjTmvWE3X2IeOeObhpD3V9pMZEjyWtBAAvF/HmTlNYtoLf87WbB8DgBxe+Hh/WX/u6o4x+aJQLJ3M5HLUm2HNJHNzlQhRiI7NUK4ycpyA8cBm14XEJ4OnWW1zPiKWySYTH1u8zRMfRt0Hd0fx7M8MDcmyZ8l04gABbMYyUn8Sw8Qj0XSWRasURiTo+C8gyRdP9WcyejNWmx/wCQRFjH3e3DaENWj2eOpfi5Eb+wRK0tunantrta/k+MM5eWQ0XK36CphYmtfKPsjsFQ7P10gYOOSa37mv9bVSlwhehMrwJqe6XW2eT1P5U5MMbQphztp+O+AoWVvf5NekMKfrGoZQ2jhxa2Q==
  template:
    metadata:
      creationTimestamp: null
      name: registry-pull-secret
      namespace: gamestore
    type: kubernetes.io/dockerconfigjson
