---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notifications-function-secret
  namespace: gamestore
spec:
  encryptedData:
    brevo-api-key: AgCCTe6PiAjWHvqABeVp0Pkpd1PlY+SfIMVUjUnw7E1AaHP51j8ybFEVy4yuH3PPNFv624MREPB4Wj6PSVlCiBXvP5vrNPC4BXlbIsDa8QleA59u98nFjpEZun3ia3XuMv7HtBLfazfP1bnVK6GLx8LD0nQzec1wKhDn9fGzJKOnnBkY7aWzgnDHIwMDOk72lyCyPZXvkdbbMxAmbcvsT67SrmGbXbDucClpL1LebLaHuKQG93khSHbX+pfDNBK7iIjW/m6yJ08oBxX6LN4WpnhHqoq0lyNzr+U3KXwBTOWz4ltfML3jWkPLBuHZgynMD21XKM1RwO2xUUV1/lWc5p/o8cz4lsBuvgAC1gSSGSNxetG8RNepGcowXJmLjpcD9TOuu/cGkBo1rdXY8veg2XVc25M0Hs/noyqQ8imN65JYm4EUlk5h1mbJ0r52LkcqYjUZFrHTyfD8hrcN6XbKlewTd5AIqT3ztNZFTHMFdejU/+jej9FWP34bpaKnV5G8uXoLpWkMdtaLeeGb+uqjlS5B8ULT7qjdRURsgib/Q2pKVVGI+bPDf+J6R+y+4USrUqvbP48bW1N1Z2xvR0hD22ggQPrc5r8U9U+ZRSAdd8JkLvUNorN+zL/gOi5jijbL4cx/ikuyAQs+Hr19J8Wvf9xSexcGQjNscZ35LnYnsOzC/BNZLX62qcMyuFQqIDlFGSwnKSbOEESRN5mhOLSW1Kn7hyXhaowsDBQhQ2BCkmOlsRFZ4QLB5uQ1PygsbTAh5jLR9MTA3g3aysGIs3y0O3CLOFGRnm8gxQewSAJJgRuXcwr2c8pP0NVMMA==
    rabbitmq-connection: AgBXDjhmgFQOS6Ac+uDNSi6MxeeSc18Idx6IY0t7Te4EO7H84j2r0t93wU5CkL2cap3HlCp+JaVhbBtEVtCqMvo4yt6kBUJtvbtly5+6UtkfaC5D9VMZd+ENM24pKk31orwmRYlljjP8hGN6/KdQEOKlLa+zkIPVl1gt1qgHr6wdfSzV1Fc5JYF0sn0uHkEQ9dTtvjY3LJXwl8Umd3T/QglYEovxWg7q/4FUuOaZy4N5mpOdFwD2TH/C80lYpgTvYwpe+FtZ5pjYJ3Cu9cCpPsdONrT9SwHIIgP2fesZqNjUiuO68u+ItjVwPD1nFaFU2xSByFMN21J6ZHuNUaM4NPXHPn+qyv42avjWFnvA5zsY1o0minqeZCI+pXYbssxkRE50GNkKsobR3ia2iM0hgYTGW5RhnlCZIJMqXFTrW8VRltx+k8DFBu3oQ5K4A5GsvOS7kxM0YTydaC5gqfwG7URXmW4YpME5xCv29v3m9FJuIh/U5V0RHbRgPH//PwS3QKlSizsWWMgQffAcSNBxXkTpKK0ZlxromspEQ/VAkmx9pWIdW8T8vBLFiA2MHQGqoJR65/aAYpWOdcF+3K+IekiAMpXSHwoLUWUCStKO+MlKPem9kVEppfwvBVQp5JA/e3Wu7cgYDi3Hrp2aqWIlwvLsl+Fpv+82pbfep7GaJQieqbvLy6jyaZ/OdLEwiwKiAEOk2AEyjA4Sufc/7ZKXABMwdXMLDLlwNkEz1QpKhLFSCCeeLAA3porYaiLM8RgMx4+FTCFUmQ6VRM6m/DCv3DJu2CGRYj+kLc200fih4/am55Vwnh82qYW1TjlvcA0=
  template:
    metadata:
      creationTimestamp: null
      name: notifications-function-secret
      namespace: gamestore
